# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88740312aac5b9b60d0e81ae638d036fff1b9147cfe497b81dad8ce542ac3523aa14c9bd9de5c682221050260d5d22b734634d56c60098449594664238220a33

test:
  secret_key_base: f600966096b9c92b7c5a4b63c2ed9fd384bfddb99d152bc36ae0522a3c13a13138e92536eeb81be6f67a3b7730218bf0893f46e4c008b3230edd53938f5f2525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
